### ISSUE TITLE
To many static

### ISSUE THREAD

**Issue by Luiggi33** [shmoe6/Site-58-Mod#1]
YEETUS DELETUS DE STATIC 
Like for real, make one AntiStatic Patch

**Comment by Luiggi33** [comment]
Please fix

**Comment by Naomiora** [comment]
Why close it when it isn't fixed

**Comment by Luiggi33** [comment]
true again

**Comment by Naomiora** [comment]
Fixed it partly, not completely

**Comment by Luiggi33** [comment]
I would assume this is done/discontinued
